# This is the configuration used to check the rubocop source code.

AllCops:
  DisabledByDefault: true
# AllCops:
#   Exclude:
#     - 'spec/*'
#     - 'lib/enigma_engine/version.rb'
#     - 'enigma_engine.gemspec'
#   TargetRubyVersion: 2.2

